language: java
jdk:
- openjdk8
script: mvn clean verify
deploy:
  provider: heroku
  api_key:
    secure: pVZAxxanlBVLkFl3aELOgRoaDtmKvG2lHY1dtltKZn+es7uwxbjXM+rlvjFeNlsC5L3Zen0cZ8tikcYO+fpR18E4Ki4QpokpnIYqoCe/8Kr/GgpO1iBmfsbhryxCXU7MJRUvd7IX9qtSahL25ShBQeoha3gR46QAvT9Q3viZu8etbHugApoW9cuNa7Lz9NRP5SvepE4Pe96sv3aeNri3DSWE3upN04QDoadZ5WqQICnPjDOTjF3P4BD/VkcVPK+rpXq97vR5K33y0tjLEjZmBuCYWxkODB3lByTtsgr8eq+gIjNxjTfm/ptB7vLVqPRSFLnjJG3lvvbma84RJ8yw4jznHZmtaZo+feyMq3ZBUBr1Fgj5GzVxAdBCUkJ1lkHzi1JBhPQp5x4HAb9WuRVdGJ80mYg4guWXYjYQ4r5K16AqThNAPh/peLKUFWzVGTdC2NCQWB79ZSJ1OcK9fP8OO3tg/1VBG2ShoNX/xegjZ8uST3V5XcevEL9FujnlBJaHG7wuqP0nyLJGMm4RQSy7ktHN6D0H31CfQqoKwopf3jKidboRwryhEBRD5hdIL+YUx9LlfyJsJEDqPQ5CSLcVtYN063YddgV4+6tWBsjyyW0+v3bqR8CjiZ8c3ulzuKiuW+4KKAQZVQxs1n5rmy7CTuy4bjSnvZ/+j/1hEUN6sSk=
  app: stark-waters-23164
